# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-26 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_auto_20170426_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='downloaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
