# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-29 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_auto_20170426_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
